services:
  mongodb:
    image: mongo
    ports:
      - 127.0.0.1:27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
      MONGO_INITDB_DATABASE: people
  
  phonebook:
    build:
      context: .
    develop:
      watch:
        - action: sync+restart
          path: ./backend
          target: /src
          initial_sync: false
          ignore:
          - node_modules/
        - action: rebuild
          path: ./frontend
    ports:
      - 127.0.0.1:3001:3001
    environment:
      MONGODB_URI: "mongodb://user:${MONGO_DB_PASSWORD}@mongodb:27017/people?authSource=admin"
    depends_on:
      mongodb:
        condition: service_started